### ISSUE TITLE
`mrate` calculation in massrep.Rmd

### ISSUE THREAD

**Issue by benthestatistician** [jghekas/KYhealth#4]
In massrep.Rmd I see

``` r
total$mrate = total$deaths/total$pops*100000
```

which R understands as 

``` r
total$mrate = ( total$deaths/total$pops ) * 100000
```

Is that what was intended?  Or was the intended calculation

``` r
total$mrate = total$deaths/( total$pops * 100000 )
```

**Comment by jghekas** [comment]
The mortality rate was reported per 100,000 people in the original paper.  I adopted a similar calculation for mortality rates within my analysis.  The calculation as is produces this value.

**Comment by benthestatistician** [comment]
Thanks for the clarification, @jghekas !
